version: "3.7"  
  
services:  
 bot:  
   image: massmux/lightningtipbot:0.5.1
   restart: on-failure  
   stop_grace_period: 1m  
   working_dir: /opt/LightningTipBot
   entrypoint: /opt/LightningTipBot/LightningTipBot
   volumes:
     - ${PWD}/config.yaml:/opt/LightningTipBot/config.yaml
     - ${PWD}/data:/opt/LightningTipBot/data
   ports:
     - "6060:6060"
     - "5454:5454"
     - "5588:5588"


  
